# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-14 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='Other', max_length=200),
            preserve_default=False,
        ),
    ]
