# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-20 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Stress', 'Stress'), ('Body Image', 'Body Image'), ('LGBTQ', 'LGBTQ'), ('Drinking and Smoking', 'Drinking and Smoking'), ('Bullying', 'Bullying'), ('Self Esteem', 'Self Esteem'), ('Peer Pressure', 'Peer Pressure'), ('Eating Disorder', 'Eating Disorder'), ('Child Abuse', 'Child Abuse'), ('Strict Parents', 'Strict Parents'), ('Underage Sex', 'Underage Sex'), ('Cyber Addiction', 'Cyber Addiction'), ('Depression', 'Depression'), ('Teen Pregnancy', 'Teen Pregnancy'), ('Sleep', 'Sleep')], default='other', max_length=200),
        ),
    ]
